version: '2'

volumes:
  standalone_data:

services:
  mysql:
    container_name: mysql57
    hostname: mysql57
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - standalone_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
