version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
    networks:
      - elasticsearch-net
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

networks:
  elasticsearch-net:

volumes:
  elasticsearch-data:
